// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Steps.Infrastructure.Data;

#nullable disable

namespace Steps.Infrastructure.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:CollationDefinition:case_insensitive", "und-u-ks-primary,und-u-ks-primary,icu,False")
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AthleteEntry", b =>
                {
                    b.Property<Guid>("AthletesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EntryId")
                        .HasColumnType("uuid");

                    b.HasKey("AthletesId", "EntryId");

                    b.HasIndex("EntryId");

                    b.ToTable("AthleteEntry");
                });

            modelBuilder.Entity("Steps.Domain.Entities.Athlete", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AgeCategory")
                        .HasColumnType("integer");

                    b.Property<Guid>("AthleteElementsId")
                        .HasColumnType("uuid");

                    b.Property<int>("AthleteType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Degree")
                        .HasColumnType("integer");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AthleteElementsId")
                        .IsUnique();

                    b.HasIndex("TeamId");

                    b.ToTable("Athletes");
                });

            modelBuilder.Entity("Steps.Domain.Entities.AthleteElements", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AgeCategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Degree")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Element1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Element2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Element3")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Element4")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Element5")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AthleteElements");

                    b.HasData(
                        new
                        {
                            Id = new Guid("96e4056b-447c-4f0b-b026-eb9c4b222f95"),
                            AgeCategory = "YoungerChildren",
                            Degree = "Higher",
                            Element1 = "Равновесие «Арабеск» (Ласточка) на любую ногу",
                            Element2 = "Кувырок вперед, кувырок назад",
                            Element3 = "Комбинация из 4х любых Чир положения рук.",
                            Element4 = "Шпагат (один любой)",
                            Element5 = "Рондат",
                            Type = "Cheer"
                        },
                        new
                        {
                            Id = new Guid("5083591d-35a5-4531-8143-37a5e0a28eda"),
                            AgeCategory = "BoysGirls",
                            Degree = "Higher",
                            Element1 = "Шпагат (два на выбор) (девочки)",
                            Element2 = "Скорпион – 1 нога (девочки)",
                            Element3 = "Переворот вперед - рондат.",
                            Element4 = "Чир прыжки: «Той тач» 2 в темп.",
                            Element5 = "Чир-положения рук: связка одна восьмерка (любые положения рук). Средний темп.",
                            Type = "Cheer"
                        },
                        new
                        {
                            Id = new Guid("9f1d2d1b-02d7-4242-8354-70471710ebd9"),
                            AgeCategory = "Youth",
                            Degree = "Higher",
                            Element1 = "Равновесие «Лук-стрела» (юниорки).",
                            Element2 = "Переворот вперед через одну руку.",
                            Element3 = "Фляк с места.",
                            Element4 = "Маховое сальто",
                            Element5 = "Связка две восьмерки: Чир-положения рук (любые) +чир прыжки (обязательно минимум 3 подряд). Быстрый темп.",
                            Type = "Cheer"
                        },
                        new
                        {
                            Id = new Guid("4a3929a1-6462-4da2-9744-d92f4702031f"),
                            AgeCategory = "Juniors",
                            Degree = "Higher",
                            Element1 = "Равновесие «Лук-стрела» (женщины).",
                            Element2 = "Шпагат (один на выбор) (девочки)",
                            Element3 = "Перекидка назад из положения сидя.",
                            Element4 = "Рондат-фляк-сальто или Рондат-сальто + рондат-фляк",
                            Element5 = "Переворот вперед-рондат-фляк.",
                            Type = "Cheer"
                        },
                        new
                        {
                            Id = new Guid("a5e9ce09-bf41-4e93-9418-581fffcfa507"),
                            AgeCategory = "YoungerChildren",
                            Degree = "First",
                            Element1 = "чир прыжок «Так»",
                            Element2 = "Кувырок вперед, кувырок назад.",
                            Element3 = "Мост из положения стоя  и лечь обратно. Фиксация 3 сек.",
                            Element4 = "Чир положение рук Лоу Ви,к Хай Ви",
                            Element5 = "«Березка»",
                            Type = "Cheer"
                        },
                        new
                        {
                            Id = new Guid("a743350f-f1b0-4238-94e7-4c6718a0355e"),
                            AgeCategory = "BoysGirls",
                            Degree = "First",
                            Element1 = "Перекидка вперед на 2 ноги.",
                            Element2 = "Стойка на руках кувырок вперед",
                            Element3 = "Чир прыжки: «Той Тач», «Пайк».",
                            Element4 = "Шпагат поперечный.",
                            Element5 = "Рондат.",
                            Type = "Cheer"
                        },
                        new
                        {
                            Id = new Guid("0f51b6ec-b247-4fae-b607-657a0b6ce962"),
                            AgeCategory = "Youth",
                            Degree = "First",
                            Element1 = "Скорпион (юниорки).",
                            Element2 = "С разбега: рондат-отскок-рондат.",
                            Element3 = "Стойка на руках.",
                            Element4 = "Переворот назад.",
                            Element5 = "Связка одна восьмерка: Чир-положения рук (любы)+чир прыжки(обязательно минимум 2 подряд). Средний темп.",
                            Type = "Cheer"
                        },
                        new
                        {
                            Id = new Guid("d6500514-1552-4e4d-94ed-46a92e605faa"),
                            AgeCategory = "Juniors",
                            Degree = "First",
                            Element1 = "Равновесие «Лук-стрела» (женщины).",
                            Element2 = "Рондат-фляк.",
                            Element3 = "Той тач + Фляк",
                            Element4 = "Маховое сальто",
                            Element5 = "Связка три восьмерки (положения рук+чир прыжки (минимум 2 подряд)+махи ногами. Средний темп.",
                            Type = "Cheer"
                        },
                        new
                        {
                            Id = new Guid("025fc91b-27ff-474f-bc1d-823a716fe7fc"),
                            AgeCategory = "YoungerChildren",
                            Degree = "Second",
                            Element1 = "Равновесие: удержание прямая нога вперёд на 90 (фиксация 3 сек)",
                            Element2 = "Складка ноги врозь , складка ноги вместе (касаясь грудью, фиксация 3 сек)",
                            Element3 = "Мост с колен и встать обратно.",
                            Element4 = "Чир положение рук Т, ломаное Т",
                            Element5 = "«Два чир-прыжка подряд: «ТАК», «Стредл»»",
                            Type = "Cheer"
                        },
                        new
                        {
                            Id = new Guid("ccb085f8-afcb-4fd5-9a9a-057965537677"),
                            AgeCategory = "BoysGirls",
                            Degree = "Second",
                            Element1 = "Складка ноги вместе, складка нови врозь (касаясь грудью, фиксация 3 сек)",
                            Element2 = "Мост из положения стоя и встать с моста.",
                            Element3 = "Колесо с опорой на две руки.",
                            Element4 = "Стойка на голове и руках.",
                            Element5 = "Чир прыжки: «ТАК», «Той Тач».",
                            Type = "Cheer"
                        },
                        new
                        {
                            Id = new Guid("b2b37324-7a23-464d-bc76-22606e9c4b81"),
                            AgeCategory = "Youth",
                            Degree = "Second",
                            Element1 = "Складка ноги вместе, складка нови врозь (касаясь грудью, фиксация 3 сек)",
                            Element2 = "Удержание ноги в положении «Легхолд» (Флажок) любая нога (юниорки).",
                            Element3 = "Переворот вперед-рондат.",
                            Element4 = "Чир-положения рук: Комбинация из минимум 8 положений.",
                            Element5 = "Чир прыжки: подряд «Так»+«Той Тач»+»Той Тач»",
                            Type = "Cheer"
                        },
                        new
                        {
                            Id = new Guid("3b9b55bb-a96c-4aa3-bbea-f34ed0c224c3"),
                            AgeCategory = "Juniors",
                            Degree = "Second",
                            Element1 = "Складка ноги вместе, складка нови врозь (касаясь грудью, фиксация 3 сек)",
                            Element2 = "Скорпион (женщины).",
                            Element3 = "С разбега: Вальсет-рондат-180рондат.",
                            Element4 = "Фляк с места.",
                            Element5 = "Стойка на руках.",
                            Type = "Cheer"
                        },
                        new
                        {
                            Id = new Guid("abd562cf-2734-480b-8e71-a1ebe491f45e"),
                            AgeCategory = "YoungerChildren",
                            Degree = "Third",
                            Element1 = "Мост из положения лежа и лечь обратно (фиксация 3 сек)",
                            Element2 = "фиксация положения лодочка на спине, фиксация положения лодочка на животе (по 3 сек)",
                            Element3 = "Кувырок вперед",
                            Element4 = "Чир положение рук Хай Ви, Лоу Ви, Ти,",
                            Element5 = "«Чир прыжок:  «ТАК»»",
                            Type = "Cheer"
                        },
                        new
                        {
                            Id = new Guid("c096b900-85b3-4059-8b8f-ecac2faf7ff9"),
                            AgeCategory = "BoysGirls",
                            Degree = "Third",
                            Element1 = "Мост из положения стоя и лечь обратно (фиксация 3 сек).",
                            Element2 = "Кувырок вперед, кувырок назад",
                            Element3 = "Равновесие «Арабеск» (Ласточка) на любую ногу",
                            Element4 = "Чир прыжки: «ТАК»+«Стредл». Два подряд.",
                            Element5 = "Положения рук: Хай Ви, Лоу Ви, Ти, Правая диагональ, Левая диагональ.",
                            Type = "Cheer"
                        },
                        new
                        {
                            Id = new Guid("f73735eb-8988-46a5-9d12-3231c5e4bd7a"),
                            AgeCategory = "Youth",
                            Degree = "Third",
                            Element1 = "Складка ноги вместе, складка нови врозь (касаясь грудью, фиксация 3 сек)",
                            Element2 = "Мост из положения стоя и встать с моста.",
                            Element3 = "Колесо с опорой на две руки.",
                            Element4 = "Стойка на голове и руках.",
                            Element5 = "Чир прыжки: «ТойТач», «хеднер»",
                            Type = "Cheer"
                        },
                        new
                        {
                            Id = new Guid("60a9c78c-3944-44fb-9a54-f9eecb766d57"),
                            AgeCategory = "Juniors",
                            Degree = "Third",
                            Element1 = "Складка ноги вместе, складка нови врозь (касаясь грудью, фиксация 3 сек)",
                            Element2 = "Удержание ноги в положении «Легхолд» (Флажок) любая нога (женщины).",
                            Element3 = "Переворот вперед-рондат",
                            Element4 = "Стойка на руках – кувырок вперед.",
                            Element5 = "Колесо с опорой на одну руку.",
                            Type = "Cheer"
                        },
                        new
                        {
                            Id = new Guid("d3cc718b-a89b-4e8c-a24b-e6e3de1fc02c"),
                            AgeCategory = "YoungerChildren",
                            Degree = "Fourth",
                            Element1 = "Пресс 10 раз (лежа на спине, ноги согнуты в коленях);",
                            Element2 = "Прыжок вокруг себя 180+180 (положение рук свободное);",
                            Element3 = "Чир прыжок «Стредл»;",
                            Element4 = "Складка нови врозь (касаясь грудью, фиксация 3 сек)",
                            Element5 = "Равновесия: «Либерти» (цапелька) на любую ногу (фиксация 3 сек)",
                            Type = "Cheer"
                        },
                        new
                        {
                            Id = new Guid("fb55a802-3c33-4c85-9500-98df715368d2"),
                            AgeCategory = "BoysGirls",
                            Degree = "Fourth",
                            Element1 = "Складка ноги вместе, складка нови врозь (касаясь грудью, фиксация 3 сек)",
                            Element2 = "Мост из положения лежа и лечь обратно (фиксация 3 сек)",
                            Element3 = "Стойка на предплечьях (березка) (фиксация 3 сек)",
                            Element4 = "Чир прыжки: «ТАК», «Стредл».",
                            Element5 = "Кувырок вперед.",
                            Type = "Cheer"
                        },
                        new
                        {
                            Id = new Guid("d346e586-66c4-49af-9237-dff934a0e1c9"),
                            AgeCategory = "Youth",
                            Degree = "Fourth",
                            Element1 = "Мост из положения стоя и лечь обратно (фиксация 3 сек)",
                            Element2 = "Кувырок вперед, кувырок назад.",
                            Element3 = "Равновесие -ласточка на любую ногу (юниорки).",
                            Element4 = "Комбинация из ЧИР положений рук, минимум 6.",
                            Element5 = "Складка ноги врозь",
                            Type = "Cheer"
                        },
                        new
                        {
                            Id = new Guid("a760ef27-25a8-41c0-a827-3e5441d27d3b"),
                            AgeCategory = "Juniors",
                            Degree = "Fourth",
                            Element1 = "Мост из положения лежа и лечь обратно (фиксация 3 сек).",
                            Element2 = "Равновесие «Арабеск» (Ласточка) на любую ногу.",
                            Element3 = "Колесо с опорой на две руки.",
                            Element4 = "Стойка на голове и руках (фиксация 3 сек).",
                            Element5 = "Связка одна восьмерка: Чир положения рук + чир прыжки. Средний темп.",
                            Type = "Cheer"
                        },
                        new
                        {
                            Id = new Guid("9768683d-59b0-43e6-a734-586af4707035"),
                            AgeCategory = "Baby",
                            Degree = "Higher",
                            Element1 = "Складка ноги вместе, складка ноги врозь. (касаясь грудью, фиксация 3 сек) ",
                            Element2 = "Упор лежа-прогиб назад,согнуть колени «Рыбка»",
                            Element3 = "Релеве на одной ноге.на всей стопе,вторая нога вытянута вперед на 30 градусов ",
                            Element4 = "Прыжок «Банана Сплит» ",
                            Element5 = "Положение рук Хай Ви ,Лоу Ви "
                        },
                        new
                        {
                            Id = new Guid("b155d139-5c0c-4fe0-8a0b-8c1a94b226cd"),
                            AgeCategory = "Baby",
                            Degree = "First",
                            Element1 = "Сед ноги врозь-складка к правой ноге. складка к левой ноге (касаясь грудью, фиксация 3 сек) ",
                            Element2 = "«Корзиночка» Лежа на животе Захват каждой рукой одноименной  согнутой ноги ",
                            Element3 = "Равновесие на одной ноге.на всей стопе,вторая нога вытянута вперед на 30 градусов ",
                            Element4 = "Прыжок «Джампинг Джэк» ",
                            Element5 = "Положение рук  «Подсвечники». «Ведра»"
                        },
                        new
                        {
                            Id = new Guid("0501c262-c743-4dc8-8073-861af0730f43"),
                            AgeCategory = "Baby",
                            Degree = "Second",
                            Element1 = "Складка ноги вместе (касаясь грудью, фиксация 3 сек) ",
                            Element2 = "«Полумост» Лежа на спине поднять таз и захватить руками пятки одноименной согнутой ноги ",
                            Element3 = "Релеве по 2 позиции на 2х ногах",
                            Element4 = "Комбинация прыжков Сотэ по 6 и 2 позиции",
                            Element5 = "Положение рук «Руки на бедрах» "
                        },
                        new
                        {
                            Id = new Guid("6e9bfde8-f6c8-4807-8c23-796a8bbfd6f8"),
                            AgeCategory = "Baby",
                            Degree = "Third",
                            Element1 = "Сед пятки вместе-колени согнуты в стороны («бабочка»).Наклон вперед в,фиксация 3 сек ",
                            Element2 = "Прогиб назад стоя на коленях,захват руками пяток «Верблюд»",
                            Element3 = "Релеве по 6 позиции на 2х ногах",
                            Element4 = "Прыжок Сотэ по 2 позиции",
                            Element5 = "Положение рук Клэп"
                        },
                        new
                        {
                            Id = new Guid("5183ad88-dde3-4410-bac9-e59bb98b114d"),
                            AgeCategory = "Baby",
                            Degree = "Fourth",
                            Element1 = "Сед на полу,ноги вытянуты- 1.стопы на себя 2-вытянуть носки",
                            Element2 = "Удержание прямых ног сидя на полу",
                            Element3 = "Положение пассе сидя на полу",
                            Element4 = "Прыжок Сотэ по 6 позиции",
                            Element5 = "Положение «Клин» (Чистая позиция)"
                        },
                        new
                        {
                            Id = new Guid("45c2dcb4-42af-4240-b984-9ca1a01fcc0c"),
                            AgeCategory = "YoungerChildren",
                            Degree = "Higher",
                            Element1 = "Шпагат (3 вида)",
                            Element2 = "Колесо с опорой на две руки",
                            Element3 = "Джазовый пируэт на 720(2 оборота)",
                            Element4 = "Чир прыжки -ТОЙ ТАЧ",
                            Element5 = "Комбинация базовых положений рук с другими элементами (прыжками, махами, вращениями и т.д.) минимум на 16 счетов",
                            Type = "CheerFreestyle"
                        },
                        new
                        {
                            Id = new Guid("e859172b-d3e5-4dc2-9ee1-d34a355c94cb"),
                            AgeCategory = "BoysGirls",
                            Degree = "Higher",
                            Element1 = "Шпагат с захватом ноги",
                            Element2 = "Колесо с опорой на одну руку ",
                            Element3 = "2разных пируэта – -Джазовый или классический на 720,-«Солнышко»",
                            Element4 = "Чир-прыжки-ХЕДЛЕР-ТОЙ ТАЧ,-ПАЙК или ДВОЙНАЯ ДЕВЯТКА",
                            Element5 = "Комбинация базовых положений рук с другими элементами (ЧИР ДАНС) (прыжками, махами, вращениями и т.д.) минимум на 24 счета",
                            Type = "CheerFreestyle"
                        },
                        new
                        {
                            Id = new Guid("b35e6105-356d-4015-aa53-14313a7a583d"),
                            AgeCategory = "Youth",
                            Degree = "Higher",
                            Element1 = "Шпагат с захватом ноги",
                            Element2 = "Элемент чир-акробатики Переворот вперед",
                            Element3 = "2 разных пируэта-Джазовый или классический на 720 минимум.(2 оборота)-Пируэт на вторую позицию (а ля секонд) минимум 3 оборота",
                            Element4 = "Комбинация чир-прыжков  в темп ХЕДЛЕР вперед или в сторону+ТОЙ ТАЧ+ТОЙ ТАЧ",
                            Element5 = "Комбинация базовых положений рук с другими элементами (ЧИР ДАНС) (прыжками, махами, вращениями и т.д.) минимум на 24 счета.",
                            Type = "CheerFreestyle"
                        },
                        new
                        {
                            Id = new Guid("1563a4af-5b1d-480e-b390-c5cc45edd212"),
                            AgeCategory = "Juniors",
                            Degree = "Higher",
                            Element1 = "Шпагат с захватом ноги",
                            Element2 = "Элементы чир-акробатики ЭРИЭЛ (маховое боковое сальто) стойка на руках",
                            Element3 = "3 разных пируэта -Джазовый или классический на 1080 (3 оборота).-Пируэт на вторую позицию (а ля секонд) минимум 4 оборота-Лэг Холд (вперед или  сторону)",
                            Element4 = "Комбинация чир- прыжков в темп ХЕДЛЕР вперед или в сторону+ТОЙ ТАЧ+ПАЙК Или СТЭГ-СИТ+ТОЙ ТАЧ+ПАЙК",
                            Element5 = "Комбинация базовых положений рук с другими элементами (прыжками, махами, вращениями и т.д.) минимум на 32 счета.",
                            Type = "CheerFreestyle"
                        },
                        new
                        {
                            Id = new Guid("ca8e56ec-5977-4b69-a8f5-c5bcf2aabe33"),
                            AgeCategory = "YoungerChildren",
                            Degree = "First",
                            Element1 = "Шпагат (2 вида)",
                            Element2 = "Кувырок вперед",
                            Element3 = "Джазовый пируэт на 360",
                            Element4 = "Чир прыжки «ХЕРДЛЕР ВПЕРЕД»",
                            Element5 = "Комбинация базовых положений рук с другими элементами (прыжками, махами,вращениями и т. д) минимум на 8 счетов ",
                            Type = "CheerFreestyle"
                        },
                        new
                        {
                            Id = new Guid("cb9b85de-f4ba-4868-aeee-379761df592a"),
                            AgeCategory = "BoysGirls",
                            Degree = "First",
                            Element1 = "Шпагат (3 вида)",
                            Element2 = "Колесо с опорой на две руки",
                            Element3 = "Джаз-пируэт на 720",
                            Element4 = "Чир прыжки –-ХЕДЛЕР вперед-ТОЙ ТАЧ",
                            Element5 = "Комбинация базовых положений рук с другими элементами  (прыжками, махами, вращениями и т.д.) минимум на 16 счетов",
                            Type = "CheerFreestyle"
                        },
                        new
                        {
                            Id = new Guid("89c11e72-1c14-4e1b-bd27-ea2bdcb3f157"),
                            AgeCategory = "Youth",
                            Degree = "First",
                            Element1 = "Шпагат (3 вида)",
                            Element2 = "Колесо с опорой на одну руку",
                            Element3 = "Два разных пируэта – -Пируэт аттитюд-«Солнышко»",
                            Element4 = "Чир-прыжки-ХЕДЛЕР вперед-ТОЙ ТАЧ,-ПАЙК",
                            Element5 = "Комбинация базовых положений рук с другими элементами (ЧИР ДАНС) (прыжками, махами, вращениями и т.д.) минимум на 16 счетов",
                            Type = "CheerFreestyle"
                        },
                        new
                        {
                            Id = new Guid("12e63ed0-9161-4985-a496-7a1295223d9f"),
                            AgeCategory = "Juniors",
                            Degree = "First",
                            Element1 = "Шпагат (3 вида)",
                            Element2 = "Сложный элемент чир акробатики с отрывом от пола (на выбор)",
                            Element3 = "2 разных пируэта-Джазовый или классический на 720 минимум.-Пируэт на вторую позицию (а ля секонд) минимум 4 оборота",
                            Element4 = "Комбинация чир-прыжков  в темп ХЕДЛЕР вперед или в сторону+ТОЙ ТАЧ+ТОЙ ТАЧ",
                            Element5 = "Комбинация базовых положений рук с другими элементами (прыжками, махами, вращениями и т.д.) минимум на 24 счета.",
                            Type = "CheerFreestyle"
                        },
                        new
                        {
                            Id = new Guid("bb966ad8-1049-49d6-889a-16c19f3d8eb1"),
                            AgeCategory = "YoungerChildren",
                            Degree = "Second",
                            Element1 = "Шпагат (один на выбор)",
                            Element2 = "Удержание вытянутой ноги (Флажок)-на любую ногу",
                            Element3 = "Повороты на двух ногах с продвижением с удержанием точки «шэне» (минимум 3)",
                            Element4 = "Чир прыжки: «ХЕРКИ»",
                            Element5 = "Комбинация из 6 базовых положений рук--Кинжалы-Тачдаун-Нижний Тачдаун-Эль (правая и левая)-Лук и стрела-Панч Ап",
                            Type = "CheerFreestyle"
                        },
                        new
                        {
                            Id = new Guid("25ab9c96-d04e-46ee-b865-2f2aec575525"),
                            AgeCategory = "BoysGirls",
                            Degree = "Second",
                            Element1 = "Шпагат (2 вида)",
                            Element2 = "Кувырок вперед",
                            Element3 = "Джаз-пируэт на 360(1 оборот) ",
                            Element4 = "Чир прыжки – ХЕРКИ-«С»джамп",
                            Element5 = "Комбинация базовых положений рук с другими элементами (прыжками, махами, вращениями и т. д) минимум на 8 счетов",
                            Type = "CheerFreestyle"
                        },
                        new
                        {
                            Id = new Guid("b3eee10b-c3c4-4c2b-b197-7c0980738025"),
                            AgeCategory = "Youth",
                            Degree = "Second",
                            Element1 = "Шпагат (2 вида)",
                            Element2 = "Колесо с опорой на две руки",
                            Element3 = "Джаз-пируэт на 720",
                            Element4 = "Чир прыжки-ХЕДЛЕР ВПЕРЕД-ТОЙ ТАЧ",
                            Element5 = "Комбинация базовых положений рук с другими элементами  (прыжками, махами, вращениями и т.д.) минимум на 16 счетов",
                            Type = "CheerFreestyle"
                        },
                        new
                        {
                            Id = new Guid("c1abc1ec-6525-4bfa-89e9-a78cc8d85952"),
                            AgeCategory = "Juniors",
                            Degree = "Second",
                            Element1 = "Шпагат (2 вида)",
                            Element2 = "Колесо с опорой на одну руку",
                            Element3 = "Два разных пируэта-Пируэт аттитюд или арабеск—-«Солнышко",
                            Element4 = "Чир-прыжки  -ХЕДЛЕР вперед или  в сторону,---ТОЙ ТАЧ,-ПАЙК",
                            Element5 = "Комбинация базовых положений рук с другими элементами (ЧИР ДАНС) (прыжками, махами, вращениями и т.д.) минимум на 16 счетов",
                            Type = "CheerFreestyle"
                        },
                        new
                        {
                            Id = new Guid("421a2115-6ef8-41a0-bd61-534fba72630d"),
                            AgeCategory = "YoungerChildren",
                            Degree = "Third",
                            Element1 = "Фиксация положения лодочка на спине, фиксация положения лодочка на животе (по 3 сек)",
                            Element2 = "Мост из положения лежа и лечь обратно. Фиксация 3 сек",
                            Element3 = "Равновесия: Положение «арабеск» на всей стопе(фиксация 3 сек) Поднятая назад нога вытянута и отведена на 45 или 90 градусов. Фиксация 3 сек.",
                            Element4 = "Чир прыжки:   «ТАК», «Стредл»",
                            Element5 = "Базовые положения рук «Правая диагональ», «Левая диагональ,»»Ти позиция»,» ломаное Т»",
                            Type = "CheerFreestyle"
                        },
                        new
                        {
                            Id = new Guid("ef1a9dbd-4ffe-4efc-b3d7-758874537b53"),
                            AgeCategory = "BoysGirls",
                            Degree = "Third",
                            Element1 = "Шпагат (один на выбор)",
                            Element2 = "Удержание вытянутой  ноги (Флажок)-на любую ногу",
                            Element3 = "Повороты на двух ногах с продвижением с удержанием точки -«шэне» (минимум 3).Фиксировать остановку.",
                            Element4 = "Чир прыжки: «Абстракт»",
                            Element5 = "Комбинация из  базовых положений рук, минимум 6 положений. Комбинация из 6 базовых положений рук--Кинжалы-Тачдаун-Нижний Тачдаун-Эль (правая и левая)-Лук и стрела-Панч Ап",
                            Type = "CheerFreestyle"
                        },
                        new
                        {
                            Id = new Guid("2f99ddbf-08f5-4001-a2e5-6511f1855aab"),
                            AgeCategory = "Youth",
                            Degree = "Third",
                            Element1 = "Шпагат (один  на выбор)",
                            Element2 = "Высокие махи вперед  и в сторону (4 маха)",
                            Element3 = "Тур пике – 3 пируэта.",
                            Element4 = "Чир прыжки –– ХЕРКИ-«С»джамп",
                            Element5 = "Комбинация из  базовых положений рук, минимум 8 положений.",
                            Type = "CheerFreestyle"
                        },
                        new
                        {
                            Id = new Guid("5fdfe987-96d8-45b3-a7f9-e6a4835cfc4f"),
                            AgeCategory = "Juniors",
                            Degree = "Third",
                            Element1 = "Шпагат (один на выбор)",
                            Element2 = "Колесо с опорой на две руки",
                            Element3 = "Джазовый пируэт минимум на 720 градусов",
                            Element4 = "Чир прыжки-ХЕРКИ,-ХЕДЛЕР вперед,",
                            Element5 = "Комбинация базовых положений рук с другими элементами (прыжками, махами, вращениями и т.д) минимум на 8 счетов.",
                            Type = "CheerFreestyle"
                        },
                        new
                        {
                            Id = new Guid("7c5c603b-1fda-40dd-adc4-2440d4938aa8"),
                            AgeCategory = "YoungerChildren",
                            Degree = "Fourth",
                            Element1 = "Складка ноги вместе, складка ноги врозь. (касаясь грудью, фиксация 3 сек)",
                            Element2 = "Стойка на лопатках «Березка»",
                            Element3 = "Равновесие на всей стопе, положение «пассе» («Либерти»)фиксация 3 сек.",
                            Element4 = "Чир прыжок «Стредл»",
                            Element5 = "Базовые положения рук Чистая позиция, Клэп, Хай Ви, Лоу Ви",
                            Type = "CheerFreestyle"
                        },
                        new
                        {
                            Id = new Guid("612b0438-7f37-4fce-9bfa-c119dfe0d4f5"),
                            AgeCategory = "BoysGirls",
                            Degree = "Fourth",
                            Element1 = "Складка ноги вместе, складка нови врозь (касаясь грудью, фиксация 3 сек)",
                            Element2 = "Мост из положения лежа и лечь обратно (фиксация 3 сек)",
                            Element3 = "Равновесия: Положение «пассе» на высоких полупальцах (фиксация 3 сек)",
                            Element4 = "Чир прыжки: «ТАК», «Стредл».",
                            Element5 = "Базовые положения рук (4 –минимум) Правая диагональ Левая диагональ Ти-позиция Ломаное Т",
                            Type = "CheerFreestyle"
                        },
                        new
                        {
                            Id = new Guid("b710091d-86db-4012-acf6-aa87da9bbb79"),
                            AgeCategory = "Youth",
                            Degree = "Fourth",
                            Element1 = "Складка ноги вместе, складка нови врозь. (касаясь грудью, фиксация 3 сек)",
                            Element2 = "Кувырок вперед",
                            Element3 = "Повороты на двух ногах с продвижением с удержанием точки -«шэне» (минимум 3)",
                            Element4 = "Чир прыжки: «Абстракт»,  «Стредл» ",
                            Element5 = "Комбинация из  базовых положений рук, минимум 6 положений.-Кинжалы-Тачдаун-Нижний Тачдаун-Эль (правая и левая)-Лук и стрела-Панч Ап",
                            Type = "CheerFreestyle"
                        },
                        new
                        {
                            Id = new Guid("5cea5f56-c86a-44e4-90dc-af315d3c6aac"),
                            AgeCategory = "Juniors",
                            Degree = "Fourth",
                            Element1 = "Высокие махи вперед  и в сторону(4 минимум)",
                            Element2 = "Кувырок вперед, кувырок назад",
                            Element3 = "Тур пике – (минимум 3 пируэта)",
                            Element4 = "Чир прыжки «Абстракт» «Си-прыжок»",
                            Element5 = "Комбинация из  базовых положений рук, минимум 8 положений.",
                            Type = "CheerFreestyle"
                        });
                });

            modelBuilder.Entity("Steps.Domain.Entities.Club", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .UseCollation("case_insensitive");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("OwnerId");

                    b.ToTable("Clubs");
                });

            modelBuilder.Entity("Steps.Domain.Entities.Contest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    NpgsqlIndexBuilderExtensions.UseCollation(b.HasIndex("Name"), new[] { "case_insensitive" });

                    b.ToTable("Contests");
                });

            modelBuilder.Entity("Steps.Domain.Entities.Entry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContestId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatorId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("boolean");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SubmissionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ContestId");

                    b.HasIndex("CreatorId");

                    b.HasIndex("TeamId");

                    b.ToTable("Entries");
                });

            modelBuilder.Entity("Steps.Domain.Entities.GroupBlocks.GroupBlock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContestId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ContestId");

                    b.ToTable("GroupBlocks");
                });

            modelBuilder.Entity("Steps.Domain.Entities.GroupBlocks.ScheduledCell", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AthleteId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExitTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GroupBlockId")
                        .HasColumnType("uuid");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId");

                    b.HasIndex("GroupBlockId");

                    b.ToTable("ScheduledCell");
                });

            modelBuilder.Entity("Steps.Domain.Entities.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .UseCollation("case_insensitive");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("OwnerId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("Steps.Domain.Entities.TestResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AthleteId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContestId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("JudgeId")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<int>>("Scores")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.HasKey("Id");

                    b.HasIndex("AthleteId");

                    b.HasIndex("ContestId");

                    b.HasIndex("JudgeId");

                    b.ToTable("TestResults");
                });

            modelBuilder.Entity("Steps.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .UseCollation("case_insensitive");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Steps.Infrastructure.Data.EntityConfiguration.ContestConfiguration+CounterContest", b =>
                {
                    b.Property<Guid>("ContestId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CounterId")
                        .HasColumnType("uuid");

                    b.HasKey("ContestId", "CounterId");

                    b.HasIndex("CounterId");

                    b.ToTable("CounterContest");
                });

            modelBuilder.Entity("Steps.Infrastructure.Data.EntityConfiguration.ContestConfiguration+JudgeContest", b =>
                {
                    b.Property<Guid>("ContestId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("JudgeId")
                        .HasColumnType("uuid");

                    b.HasKey("ContestId", "JudgeId");

                    b.HasIndex("JudgeId");

                    b.ToTable("JudgeContest");
                });

            modelBuilder.Entity("AthleteEntry", b =>
                {
                    b.HasOne("Steps.Domain.Entities.Athlete", null)
                        .WithMany()
                        .HasForeignKey("AthletesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Steps.Domain.Entities.Entry", null)
                        .WithMany()
                        .HasForeignKey("EntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Steps.Domain.Entities.Athlete", b =>
                {
                    b.HasOne("Steps.Domain.Entities.AthleteElements", "AthleteElements")
                        .WithOne()
                        .HasForeignKey("Steps.Domain.Entities.Athlete", "AthleteElementsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Steps.Domain.Entities.Team", "Team")
                        .WithMany("Athletes")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AthleteElements");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Steps.Domain.Entities.Club", b =>
                {
                    b.HasOne("Steps.Domain.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Steps.Domain.Entities.Entry", b =>
                {
                    b.HasOne("Steps.Domain.Entities.Contest", "Contest")
                        .WithMany("Entries")
                        .HasForeignKey("ContestId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("Steps.Domain.Entities.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatorId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("Steps.Domain.Entities.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contest");

                    b.Navigation("Creator");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Steps.Domain.Entities.GroupBlocks.GroupBlock", b =>
                {
                    b.HasOne("Steps.Domain.Entities.Contest", "Contest")
                        .WithMany()
                        .HasForeignKey("ContestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contest");
                });

            modelBuilder.Entity("Steps.Domain.Entities.GroupBlocks.ScheduledCell", b =>
                {
                    b.HasOne("Steps.Domain.Entities.Athlete", "Athlete")
                        .WithMany()
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Steps.Domain.Entities.GroupBlocks.GroupBlock", "GroupBlock")
                        .WithMany("Schedule")
                        .HasForeignKey("GroupBlockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Athlete");

                    b.Navigation("GroupBlock");
                });

            modelBuilder.Entity("Steps.Domain.Entities.Team", b =>
                {
                    b.HasOne("Steps.Domain.Entities.Club", "Club")
                        .WithMany("Teams")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Steps.Domain.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Club");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Steps.Domain.Entities.TestResult", b =>
                {
                    b.HasOne("Steps.Domain.Entities.Athlete", "Athlete")
                        .WithMany()
                        .HasForeignKey("AthleteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Steps.Domain.Entities.Contest", "Contest")
                        .WithMany()
                        .HasForeignKey("ContestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Steps.Domain.Entities.User", "Judge")
                        .WithMany()
                        .HasForeignKey("JudgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Athlete");

                    b.Navigation("Contest");

                    b.Navigation("Judge");
                });

            modelBuilder.Entity("Steps.Infrastructure.Data.EntityConfiguration.ContestConfiguration+CounterContest", b =>
                {
                    b.HasOne("Steps.Domain.Entities.Contest", null)
                        .WithMany()
                        .HasForeignKey("ContestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Steps.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("CounterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Steps.Infrastructure.Data.EntityConfiguration.ContestConfiguration+JudgeContest", b =>
                {
                    b.HasOne("Steps.Domain.Entities.Contest", null)
                        .WithMany()
                        .HasForeignKey("ContestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Steps.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("JudgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Steps.Domain.Entities.Club", b =>
                {
                    b.Navigation("Teams");
                });

            modelBuilder.Entity("Steps.Domain.Entities.Contest", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("Steps.Domain.Entities.GroupBlocks.GroupBlock", b =>
                {
                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("Steps.Domain.Entities.Team", b =>
                {
                    b.Navigation("Athletes");
                });
#pragma warning restore 612, 618
        }
    }
}
